### ISSUE TITLE
Support for haploid markers

### ISSUE THREAD

**Issue by eriqande** [eriqande/rubias#14]
From Kyke Shedd:

Any chance you are planning to extend the model to accept haploid data (mitochondrial SNPs, linked SNPs, etc.)? Unfortunately for us here in AK, some of our baselines depend on these haploid markers to separate out tricky populations. This is a big constraint for us when we look around for programs to implement MSA.

**Comment by eriqande** [comment]
I think we could probably come up with a hack that make sense.  It would likely involve coding the second instance of each gene copy in each individuals at each haploid locus as missing, and then having the user specify which loci are haploid and then changing the likelihood calculation for those.

**Comment by krshedd** [comment]
Ideally this could be further extended to include linked haploid markers (i.e. multiple mitochondrial SNPs, such that you have more than 2^n alleles), but I suppose that could be tricky with your 2 column format. It would have to allow for additional columns (e.g. for 3 sockeye mitochondrial SNPs: One_CO1.One_Cytb_17.One_Cytb_26, One_CO1.One_Cytb_17.One_Cytb_26.1, One_CO1.One_Cytb_17.One_Cytb_26.2, ..., One_CO1.One_Cytb_17.One_Cytb_26.7).

**Comment by eriqande** [comment]
Yes, but if they are really completely linked and haploid (on the mtDNA), then couldn't each combination of n SNPs be recorded as its own allele?  Like a microhaplotype?

**Comment by krshedd** [comment]
Yes, like a microhaplotype, that is what I was suggesting with the extra columns. but now see what you are saying. You could keep the 2 column format and just code the alleles as 1:n in the 1st column. Much simpler. Good catch.

**Comment by eriqande** [comment]
OK, I have been working on this in the branch `add-haploid-markers`.  Available on GitHub now as:

https://github.com/eriqande/rubias/tree/add-haploid-markers

I think I have all the code in place and it passes all the CRAN checks and runs the examples in the README as expected.  The README describes how to code up haploid markers (basically just make sure that the second column for each haploid marker is NA for everyone, then it will be treated as haploid.

For testing, the package can be installed like this:

```r
devtools::install_github("eriqande/rubias", ref = "add-haploid-markers")
```
Kyle, I think this is pretty close to being ready to go.  It would be helpful if you could send me a data file with mtDNA snps in it that you might use.  I would like to run it through rubias and gsi_sim to compare results.  When it is ready to go I will merge it into master.

Thanks!

**Comment by eriqande** [comment]
I think this is done.  I merged ae325614958df77dbb1c60da6a3947a481b88d5a into master.  We'll see how it goes.  Can be reopened if there are any issues.

**Comment by krshedd** [comment]
Hey Eric, sorry to be so slow in getting back to you, but I'm not sure the `self_assign`, `assess_reference_loo`, and `assess_reference_mc` functions are treating haploid data correctly. I got the same likelihood results with and without 3 haploid markers (1 mtDNA, 2 linked diploid markers). Take a look and see what you think. I'll e-mail you an .RData file (can't upload here as not a supported file type).

**Comment by eriqande** [comment]
I think something must have gotten gooched up and you didn't have the latest version.  Thanks for putting rubias to the test!  I appreciate knowing what you find with the updated version!
