### ISSUE TITLE
Duplicate Samples

### ISSUE THREAD

**Issue by CGWallace** [eriqande/rubias#23]
Would it be possible to include a Function to detect (near) duplicate samples in Mixture or Baseline - similar to GSI_SIM.

Colin Wallace

**Comment by eriqande** [comment]
Hey Colin,

I put in a quick function and updated the README to talk about it.  Check it out and tell me if that is useful for you guys!

**Comment by CGWallace** [comment]
Eric:

This is working well for me thanks.

Had to go through a bit to install the latest version of rubias for windows 7.

First I had to update “rtools” – note this is not an R package but a collection of resources for building packages for R under Microsoft Windows –

1>    Uninstall from windows programs.

2>    Also install using latest version from:

https://cran.r-project.org/bin/windows/Rtools/

#Manually remove and install a couple of core packages
remove.packages("devtools")
install.packages("devtools")
remove.packages("Rcpp")
install.packages("Rcpp")
remove.packages("rlang")
install.packages("rlang")
remove.packages("rubias")

#Ensure that devtools doesn't try to call RStudio's build tools
#detection code and just assume that everything is available.
options(buildtools.check = function(action) TRUE)

devtools::install_github("eriqande/rubias")


Colin Wallace

**Comment by eriqande** [comment]
Cool.  Glad to hear that it is working for you.  Thanks for the outline of
what it takes to install on Windows.  That will be helpful to other windows
users.

eric
