### ISSUE TITLE
Error in infer_mixture

### ISSUE THREAD

**Issue by EmiCarr** [eriqande/rubias#25]
Hi,

I am having trouble with the file format for rubias. I used genepopedit to convert a genepop to a rubias file, however, it seems there is a problem with the repunit column. When I run this script : 
mixture_analysis_2016 = infer_mixture(reference = RubiasInput_reference,
                                      mixture = RubiasInput_assign_2016,
                                      gen_start_col = 5,
                                      method = "MCMC",
                                      reps = 2000,
                                      burn_in = 100,
                                      pb_iter = 100)
I get this message :
« Error in check_refmix(reference, gen_start_col, "reference") : 
  Column "repunit" must be a character vector.  It is not in reference data frame »

Before running the script, I made sure the column was a character vector with « as.character(RubiasInput_reference$repunit) » 

Have you seen this error before?

Thanks a lot

**Comment by eriqande** [comment]
Hi Emi,

I've seen this before.  The repunit column has to be a character vector.  Are you sure that `RubiasInput_reference$repunit` is really a character vector?

Just doing:
```
as.character(RubiasInput_reference$repunit)
``` 
won't make it so.  You'd have to do:
```
RubiasInput_reference$repunit <- as.character(RubiasInput_reference$repunit)
```

Be sure to check whether it is a character vector with:
```
typeof(RubiasInput_reference$repunit)
```
If it is a character vector and the problem persists, then send me `RubiasInput_reference` and `RubiasInput_assign_2016` and I can try troubleshooting that for you.

If changing it to a character vector makes it work, it would be great if you could file an issue with genepopedit that repunit columns have to be character vectors.

Cheers,

eric

**Comment by CGWallace** [comment]
Emi:

I ran into this a while back and Eric provided me with a solution.
This also covers the possible issue of columns of Genetic data need to be of type "integer".

gen_start_col<-5
non_genetic_cols <- c(1:(gen_start_col-1))

# Format cols to character or integer required for "infer_mixture"
rubias_base[, non_genetic_cols] <- lapply(X = rubias_base[,non_genetic_cols], FUN = as.character)
rubias_base[,gen_start_col:ncol(rubias_base)] <- lapply(X = rubias_base[, gen_start_col:ncol(rubias_base)], FUN = as.integer)


Colin
