### ISSUE TITLE
ploidy mismatch error - diploid data in the baseline, but assumed haploid in the mixture due to missing data

### ISSUE THREAD

**Issue by LoganMMaxwell** [eriqande/rubias#32]
Hello,

I am running into an issue when trying to run infer_mixture on a dataset which has some missing data. My understanding is that because some of the individuals in the mixture dataset have missing data at all individuals for some loci (which are not missing at everything in the baseline), the program is confused about ploidy of the data and trying to incorrectly run it as haploid. Seems that others have had this issue, and the work-around was to remove these loci from both the reference and mixture dataset (#18 #19 ). Here is the error code, which appears the same as in previous issue conversations.

```
Error in infer_mixture(reference = TEST3, mixture = GALAPAGOS_final, gen_start_col = 5) : 
  Ploidy mismatch in reference and mixture data sets at loci 5810161721242731353840486268748586911341361411551571601611631641661751761801821941992192312342402622742822832862932983143163173243263273353463623723733753793873883913963994084134194204244304354384584924985135145175235365505535615625645675725785865925945975996026056116176186196276406486576636826877247277337517597637677697727827837978028038048108168178518628638718748798858968979029049079239249269339359379409439479499919929971000100310041007100910111020102710451066107210731074109110921093109811141116111811321136113911471160117111731175117811841196120212091213121612171223122412251226122712291234123712521255126012641271127912851297130013061311132713421347135013851387138813911392139914111414141714181431144114451458146714711475147814801489149114921494149515011505151115151519152215281536154415461548155115571561156315671579158815891594160516091611162616481679168016861699171317141734175717641769177117811782178617881796179718041
```

Wondering if there has been any progress made to address this problem within the command, or if the most efficient way is to still remove loci from the two datasets? If so, do you have any suggestions for how to streamline this process? (I have 3,000+ markers so don't want to dig through those manually).

Thanks so much for any help!

**Comment by eriqande** [comment]
Hi Logan,

Sorry to not get back to you more promptly.  I haven't made any progress on this, but it should not be hard.  Your query is just what I need to get it done!

Could you send me a sample baseline and test data set that you have which has this problem so that I can be sure my changes are properly solving your issue.  You can send them to

eric.anderson   
at
noaa
dot
gov

if you would like.

BTW, I just had a nice chat with Kris in your lab.  

have a great day.

eric

**Comment by eriqande** [comment]
Hi Logan,

Thanks for the prompting and the test data sets.  I've fixed this now (I hope!)

Have a great day.

eric
