### ISSUE TITLE
Make an empirical prior option for allele freqs.

### ISSUE THREAD

**Issue by eriqande** [eriqande/rubias#4]
It would be nice to have the option to use the reference-data-set wide allele freqs to form an empirical prior on allele frequencies (the way Pella and Masuda do).  

This will be an option that gets passed to, for example, `infer_mixture` and `assess_reference_loo`---basically all of the top-level functions.  Let's call it `alle_freq_prior`.  Let's say we pass it in as a named list.  If it is "unit_info" then we do the unit-information prior.  That is the default.  If it is "const" then it has a value which is the constant value for every allele.  If it is "const_scaled" then we do that constant divided by the number of alleles.  (so, unit-information is a special case of that).
And if it is "empirical" then we take the observed allele freqs across the whole data set and multiply that by the value given (typically going to be 1.0).

Now, the value of this will have to be passed into: `list_diploid_params()`.  We should have a function that checks to make sure `alle_freq_prior` is valid, and then we modify lines of code around here:

https://github.com/eriqande/rubias/blob/0cf57a5c38020538fbe4a13d622a465b28a3d272/R/data_conversion.R#L334-L336

To do the appropriate thing for each option.  Note that `AC_list` is a list of matrices (one for each locus) of allele counts (number of alleles in rows, and number of pops in columns), so we can just rowSum those guys to count up all the alleles, and then normalize them to get the observed, whole-data allele freqs.

**Comment by eriqande** [comment]
It would look like:

```r
list_diploid_params(..., alle_freq_prior = list(unit_info = 10) )
```

**Comment by eriqande** [comment]
Or we could do:
```r
list_diploid_params(..., alle_freq_prior = list(const_scaled = 1.5) )
```
in which case the prior dirichlet parameter value for each allele at a locus is going to be 

1.5/K 

where K is the number of alleles at the locus.

**Comment by eriqande** [comment]
Hey Ben, I just had a thought while I was writing the paper---what happens with alleles that appear in the mixture but not in the reference?  I just wanted to make sure that in infer_mixture() the empirical prior is applied after accounting for alleles in the mixture, and does we end up with a prior of zero for any allele not seen in the reference sample?  

If this is a problem, I think we should address it by simply adding 1 gene copy to the pool used for computing the relative frequencies for every allele in the mixture not seen in the reference (or we could make it simple and just add one copy for every allele seen in the mixture, regardless of whether or not it was seen in the reference.  

You probably will be busy wrassling genomes for the next few weeks, and this is not urgent, but it is something that we will want to keep in mind.

**Comment by benmoran11** [comment]
I think that the empirical prior should handle mixture-only alleles well. The alleles included in the prior are those found in the "allele count list" step of the data conversion, so it should be fine in every case where the creation of that list includes both the reference and the mixture. The infer_mixture() function checks out in this sense, so I think we're good! But I haven't actually confirmed it with any examples.

**Comment by eriqande** [comment]
Great, thanks.

That sounds good.  The only issue I can see arising is if the counts include gene copies from the mixture, the mixture is large, and the mixture is largely composed of fish that are not from the reference.  Then the occurrence of large numbers of alleles in the mixture might make those mixture fish not as noticeably outside of what one would expect (i.e. z-scores).  But, then again, that would really only happen if the constant in the empirical prior was quite large.  So, then, it is all good.

But, does that mean that the empirical prior when doing `infer_mixture()` is actually based on the relative frequencies of all the alleles in both the reference and the mixture, rather than just in the reference?  If so, I will update the paper.  Cool!

**Comment by benmoran11** [comment]
I hadn't thought it through, but yes, that is what it means! So I guess it's not built from "reference-data set wide" allele frequencies, like originally asked.

**Comment by eriqande** [comment]
OK, great.  will update the paper, and good to know how this works.  Closing it!
